### ISSUE TITLE
Light box adjustments for macro moths

### ISSUE THREAD

**Issue by Gomismis** [NHMDenmark/Pinned-Insects-workstation#117]
We have found that the top holes of WORKPIOF0002 (NHMD) and WORKPIOF0003 (NHMA) are too small for the macromoth settings as the sides are showing on the pictures. The diameter needs to be 2cm more.
 
Adjustment plans will be:

- [x] Make wood shop Kim cut a bigger hole in the light box of WORKHER0002.
- [x] Exchange the light box from WORKHERB0002 with WORKHERB0003 at NHMA (end October).
- [x] Cut a bigger hole in the light box from WORKHERB0003 
- [x] Reinstall light box from WORKPIO0003 in 411

**Comment by RebekkaML** [comment]
Matilde brought the lightbox from PIOF0002 to the woodshop yesterday and I picked it up today. I reinstalled and tested it and the hole is now big enough to image the macromoth stage. The best setting I found for this was a camera height of 69,6 cm and a depth of 12,8 cm.

**Comment by Gomismis** [comment]
AAU decided that they could fix the hole size themselves, so we have just kept our own box and @hansviborg will deal with their box.

**Comment by chelseagraham** [comment]
In our Aarhus catch-up today, Hans confirmed that he received Matilde's email with the measurement (2 cm larger). They will alter their lightbox when it makes the most sense for them.

**Comment by chelseagraham** [comment]
Alterations have been made at SNM. 
NHMA declined the offer to received our altered lightbox because they can do it in-house. 💪
@Gomismis has provided Hans with the measurements Kim Nielsen used to alter our lightbox at SNM.
These measurements were discussed by @RebekkaML and @chelseagraham at the Aarhus Catch-up in week 44 and the 31 October DaSSCo Digitization Pinned Insect Catch-up Meeting.
